# Generated by Django 4.0.4 on 2022-05-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian_word', models.CharField(max_length=100, verbose_name='Слово на русском')),
                ('english_word', models.CharField(max_length=100, verbose_name='Слово на английском')),
                ('difficult', models.IntegerField(default=1, verbose_name='Сложность(1-10)')),
            ],
        ),
        migrations.CreateModel(
            name='KnownWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KnownPercent', models.IntegerField(default=0, verbose_name='Процент знания')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.englishword')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='words',
            field=models.ManyToManyField(to='users.knownwords'),
        ),
    ]
