# Generated by Django 4.0.4 on 2022-05-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_englishword_knownwords_customuser_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='words',
            field=models.ManyToManyField(blank=True, to='users.knownwords'),
        ),
    ]
