# Generated by Django 4.0.4 on 2022-05-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='words_points',
            field=models.IntegerField(default=0, verbose_name='Очков в словах'),
        ),
    ]
