# Generated by Django 4.0.4 on 2022-05-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_words_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='words_points_record',
            field=models.IntegerField(default=0, verbose_name='Рекорд в очках'),
        ),
    ]
