# Generated by Django 4.0.4 on 2022-05-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_words_points_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='word_id',
            field=models.IntegerField(default=0, verbose_name='id текущего слова'),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='english_word',
            field=models.CharField(max_length=100, unique=True, verbose_name='Слово на английском'),
        ),
    ]
