# Generated by Django 4.0.4 on 2022-05-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_word_id_alter_englishword_english_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='word_id',
            field=models.IntegerField(default=-1, verbose_name='id текущего слова'),
        ),
    ]
