# Generated by Django 4.0.4 on 2022-05-27 17:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KnownPercent', models.IntegerField(default=0, verbose_name='Процент знания')),
            ],
        ),
        migrations.CreateModel(
            name='TrashWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian_word', models.CharField(max_length=100, verbose_name='Слово на русском')),
                ('english_word', models.CharField(max_length=100, unique=True, verbose_name='Слово на английском')),
            ],
        ),
        migrations.CreateModel(
            name='UsersDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назване словаря')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Пароль для доступа')),
                ('creator', models.CharField(max_length=100, verbose_name='Автор словаря')),
                ('creation_time', models.DateField(verbose_name='Дата создания')),
                ('difficult_lvl', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Сложность')),
                ('words', models.ManyToManyField(blank=True, to='users.dictword')),
            ],
        ),
        migrations.AddField(
            model_name='dictword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trashword'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dict_words',
            field=models.ManyToManyField(blank=True, to='users.dictword'),
        ),
    ]
