# Generated by Django 4.0.4 on 2022-05-28 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_word_dictwordid_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictwordid',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.dictword'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersdictionary',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usersdictionary',
            name='creator',
            field=models.CharField(blank=True, max_length=100, verbose_name='автор'),
        ),
    ]
