# Generated by Django 4.0.4 on 2022-05-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_dictwordid_word_alter_usersdictionary_creation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdictionary',
            name='creator',
        ),
        migrations.AddField(
            model_name='usersdictionary',
            name='creator_id',
            field=models.IntegerField(default=1, verbose_name='автор'),
        ),
    ]
