# Generated by Django 4.0.4 on 2022-05-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_usersdictionary_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashword',
            name='english_word',
            field=models.CharField(max_length=100, verbose_name='Слово на английском'),
        ),
    ]
